[features]
seeds = false
skip-lint = false

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "https://mainnet.helius-rpc.com/?api-key=629da07c-1991-41dc-9ab0-b01d7b700c02"
wallet = "deploy-wallets/treasury-mainnet.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
client = "yarn run ts-node client/*.ts"

[toolchain]
anchor_version = "0.29.0"